# Generated by Django 5.0.4 on 2026-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_icon_class_alter_certification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_static_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
