# Generated by Django 5.0.4 on 2026-04-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_video_static_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_image_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='static_image_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
