# Generated by Django 5.0.4 on 2026-04-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_static_image_1_project_static_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='static_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
