# Generated by Django 5.0.4 on 2026-04-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_image_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='static_image_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
